### ISSUE TITLE
f776 is created with wrong subfield order

### ISSUE THREAD

**Issue by ammsalme** [NatLibFi/melinda-eresource-tool#28]
When field 776 is created from 020, it should have subfield order $i $z instead of $z $i.

Current  result:
`776 08 ‡z9781292220178‡iPainettu:`

Correct result:
`776 08 ‡iPainettu:‡z9781292220178`

f.e 
https://muuntaja.melinda.kansalliskirjasto.fi/#/record/011488351

**Comment by aatuny** [comment]
Fixed https://github.com/NatLibFi/melinda-eresource-tool/commit/be752a99ad0ff52f7db6e8a1e960348bf33f63b4
