### ISSUE TITLE
f264 should copy 

### ISSUE THREAD

**Issue by ammsalme** [NatLibFi/melinda-eresource-tool#31]
In all/most profiles.

**Comment by aatuny** [comment]
Requested also by users

**Comment by aatuny** [comment]
260/264 in source record should become 264 where 2. indicator is '1'.

**Comment by aatuny** [comment]
Fixed https://github.com/NatLibFi/melinda-eresource-tool/commit/be752a99ad0ff52f7db6e8a1e960348bf33f63b4
